const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');const fs=require('fs');
const base=process.env.CHECK_BASE||'http://127.0.0.1:4173',output='.runtime/admin-console-v2';fs.mkdirSync(output,{recursive:true});
(async()=>{const b=await chromium.launch({args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1475,height:1080}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/ui/admin.html');await p.waitForFunction(()=>document.querySelector('#connection-label').textContent.includes('已连接'));await p.evaluate(()=>document.fonts.ready);await p.evaluate(async()=>{const image=new Image();image.src='assets/ev-photo.png';await image.decode()});assert(await p.locator('.vehicle-art img').evaluate(e=>e.complete&&e.naturalWidth>0));assert.equal(await p.locator('#vehicle-select option').count()>=3,true);
for(const [width,height] of [[1475,1080],[1366,900],[1920,1080],[390,844]]){await p.setViewportSize({width,height});for(const page of ['dashboard','station','trips','history']){await p.locator(`[data-page="${page}"]`).click();assert.equal(await p.locator('.page.active').count(),1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,`overflow ${page} at ${width}`);if(width===1475)await p.screenshot({path:`${output}/final-${page}.png`,fullPage:true});}}await p.setViewportSize({width:1475,height:1080});await p.locator('[data-page="station"]').click();await p.locator('#nearby-search').fill('不存在的站点xyz');assert.match(await p.locator('#navigation-stations').innerText(),/没有匹配/);await p.locator('#nearby-search').fill('');const directions=p.locator('[data-direction]');if(await directions.count()){await directions.first().click();assert((await p.locator('#turn-address').innerText()).length>0)}await p.locator('#navigation-map [data-map="in"]').click();assert.match(await p.locator('#navigation-map .map-layer').getAttribute('style'),/1.2/);await p.locator('#navigation-map [data-map="center"]').click();
await p.locator('[data-page="dashboard"]').click();await p.locator('#goal-period').selectOption('week');await p.locator('#goal-period').selectOption('today');if(process.env.CHECK_MUTATIONS!=='1'){await p.locator('#stat-period').selectOption('historical');await p.waitForFunction(()=>document.querySelector('#flow-chart').textContent.includes('2023'));await p.locator('#stat-period').selectOption('reference');}await p.locator('.console-footer [data-action="users"]').click();await p.locator('#manager-search').fill('不会存在的手机号');assert.match(await p.locator('#drawer-content').innerText(),/暂无记录/);await p.locator('[data-close="drawer"]').click();await p.locator('[data-action="account"]').click();assert.match(await p.locator('#drawer-content').innerText(),/全部管理权限/);await p.locator('[data-close="drawer"]').click();
console.log('PASS four pages at 1475/1366/1920/390 widths; image, map zoom, station search, goals, management search, admin identity; no page overflow');
if(process.env.CHECK_MUTATIONS==='1'){
 assert(base==='http://127.0.0.1:4175','Mutations only allowed on isolated test server');
 const phone='1'+String(Date.now()).slice(-10),name='UI验收'+String(Date.now()).slice(-5);
 const closeDrawer=async()=>{if(await p.locator('#drawer').isVisible())await p.locator('[data-close="drawer"]').click()};
 const submit=async()=>{await p.locator('#submit-edit').click();await p.locator('#editor').waitFor({state:'hidden'});await p.waitForFunction(()=>!document.querySelector('#submit-edit').disabled)};
 await p.locator('.console-footer [data-action="users"]').click();await p.locator('[data-action="new-users"]').click();await p.locator('[name="nickname"]').fill(name);await p.locator('[name="phone"]').fill(phone);await submit();
 let row=p.locator('#drawer tr').filter({hasText:phone});await row.locator('[data-command="edit-user"]').click();await p.locator('[name="nickname"]').fill(name+'改');await submit();assert.match(await row.innerText(),new RegExp(name+'改'));
 await row.locator('[data-command="money"]').click();await p.locator('[name="amount"]').fill('50');await p.locator('[name="reason"]').fill('浏览器验收');await submit();assert.match(await row.innerText(),/50.00/);
 const uid=await row.locator('[data-command="money"]').getAttribute('data-id');await row.locator('[data-command="wallet"]').click();await p.waitForFunction(()=>document.querySelector('#drawer-title').textContent.startsWith('钱包'));assert.match(await p.locator('#drawer-content').innerText(),/余额调整/);await closeDrawer();
 await p.locator('[data-page="trips"]').click();await p.locator('[data-action="book"]').click();await p.locator('[name="user_id"]').selectOption(uid);await submit();
 row=p.locator('#trips-table tr').filter({hasText:phone}).first();await row.locator('[data-command="start"]').click();await row.locator('.status.charging').waitFor();await p.waitForTimeout(1200);await row.locator('[data-command="stop"]').click();await row.locator('.status.completed').waitFor();await row.locator('[data-command="refund"]').click();await p.locator('[name="amount"]').fill('0.01');await p.locator('[name="reason"]').fill('浏览器退款');await submit();
 await p.locator('[data-page="history"]').click();assert.match(await p.locator('#history-table').innerText(),/退款已处理/);const downloadPromise=p.waitForEvent('download');await p.locator('[data-action="export-logs"]').click();const dl=await downloadPromise;assert.match(dl.suggestedFilename(),/\.csv$/);
 await p.locator('.topbar [data-action="settings"]').click();await p.locator('[name="daily_goal"]').fill('61');await submit();await p.locator('[data-page="dashboard"]').click();assert.match(await p.locator('#daily-value').innerText(),/61/);await p.reload();await p.waitForFunction(()=>document.querySelector('#daily-value').textContent.includes('61'));
 console.log('PASS real isolated UI user create/edit, wallet adjustment/ledger, booking/start/stop/refund, settings persistence, CSV download');
}
assert.deepEqual(errors,[]);await b.close();console.log('PASS no browser JavaScript errors')})().catch(e=>{console.error(e);process.exit(1)})
