const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const assert=require('node:assert/strict');
const base=process.env.CHECK_BASE||'http://127.0.0.1:4173';
(async()=>{const b=await chromium.launch({args:['--no-sandbox',...(process.env.CHECK_IP?['--host-resolver-rules=MAP '+new URL(base).hostname+' '+process.env.CHECK_IP]:[])]});const p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/ui/mobile.html',{waitUntil:'domcontentloaded',timeout:90000});await p.locator('#home-map canvas').waitFor();assert(await p.locator('.front-car').evaluate(e=>e.complete&&e.naturalWidth>0));await p.locator('.tab-bar [data-screen="stats"]').click();await p.waitForFunction(()=>document.querySelector('#stats-energy').textContent!=='—');const monthly=await p.locator('#stats-energy').innerText();await p.locator('[data-period="year"]').click();assert.notEqual(await p.locator('#stats-energy').innerText(),monthly);await p.locator('.schedule-link').click();assert.equal(await p.locator('.tariff-row').count(),24);await p.locator('[data-tariff="low"]').click();const low=await p.locator('.tariff-row').count();assert(low>0&&low<24);await p.locator('[data-tariff="high"]').click();assert((await p.locator('.tariff-row').count())>0);assert((await p.locator('.tariff-row').first().innerText()).includes('高价'));
await p.evaluate(()=>showScreen('map'));await p.locator('#map-search').fill('龙华');assert.match(await p.locator('#station-name').innerText(),/龙华/);await p.locator('#detail-button').click();await p.locator('.connector').first().waitFor({state:'attached'});assert.match(await p.locator('#selected-connector-label').innerText(),/UEV/);await p.locator('#charge-limit').selectOption('100');assert.equal(await p.locator('#estimated-energy').innerText(),'36.0 kWh');await p.locator('.connector-picker summary').click();await p.locator('[data-kind="fast"]').click();assert((await p.locator('.connector').count())>0);await p.locator('.connector').first().click();await p.locator('.connector-picker summary').click();await p.locator('#reserve-button').click();assert(await p.locator('#login-dialog').isVisible());await p.locator('#login-dialog .dialog-close').click();
for(const [width,height] of [[390,844],[360,740],[430,932],[1280,900]]){await p.setViewportSize({width,height});for(const screen of ['home','map','detail','charge','stats','schedule']){await p.evaluate(s=>showScreen(s),screen);await p.waitForTimeout(120);assert.equal(await p.locator('.mobile-screen.active').count(),1);const overflow=await p.locator('.mobile-screen.active').evaluate(e=>e.scrollWidth>e.clientWidth+2);assert.equal(overflow,false,`${screen} horizontal overflow at ${width}`);if(['charge','map'].includes(screen)){const control=p.locator(screen==='charge'?'#stop-button':'#detail-button');const r=await control.boundingBox();assert(r.y+r.height<=height+1,`${screen} bottom control clipped`)}if(width===390)await p.screenshot({path:`.runtime/app-reference/final-${screen}.png`})}}
// An isolated browser API fixture exercises the UI order lifecycle without making database mutations.
const q=await b.newPage({viewport:{width:390,height:844}});q.on('pageerror',e=>errors.push(e.message));await q.addInitScript(()=>localStorage.setItem('charging_user_token','ui-fixture'));let stopped=false,created=false;
const order={id:'ui-fixture-order',status:'charging',energy_kwh:'0',amount:'0',station_name:'测试站点',charger_code:'FIXTURE-1'};
await q.route('**/me',r=>r.fulfill({json:{nickname:'界面测试',phone:'13800000000',balance:'100'}}));await q.route('**/me/orders?*',r=>r.fulfill({json:[]}));await q.route('**/orders',r=>{assert.equal(r.request().method(),'POST');created=true;return r.fulfill({json:order})});await q.route('**/orders/ui-fixture-order**',r=>{if(r.request().url().endsWith('/stop'))stopped=true;return r.fulfill({json:{...order,status:stopped?'completed':'charging'}})});
await q.goto(base+'/ui/mobile.html',{waitUntil:'domcontentloaded',timeout:90000});await q.waitForFunction(()=>stations.length>0);await q.evaluate(()=>openDetail());await q.locator('#reserve-button').click();await q.waitForFunction(()=>document.querySelector('#stop-button').textContent.includes('结束充电'));assert(created);await q.waitForTimeout(2200);assert.equal(await q.locator('#charge-cost').innerText(),'0.00');assert.equal(await q.locator('#charge-energy').innerText(),'0.0');await q.locator('#stop-button').click();assert(stopped);await q.waitForTimeout(1000);assert(await q.locator('#screen-orders').isVisible());assert.deepEqual(errors,[]);await b.close();console.log('PASS: six screens, 4 viewport sizes, map/station search, charger filters/selection, charge limit estimate, login gate, historical statistics/tariff filters, isolated reserve-start-poll-stop UI flow (zero amounts preserved), no JavaScript errors.')})().catch(e=>{console.error(e);process.exit(1)})
